export type TSConfig = Partial<{
    files: string[];
    extends: string;
    include: string[];
    exclude: string[];
    references: {
        path: string;
    }[];
    compilerOptions: CompilerOptions;
    watchOptions: WatchOptions;
    typeAcquisition: TypeAcquisition;
}>
export type CompilerOptions = Partial<{
    allowUnreachableCode: boolean;
    allowUnusedLabels: boolean;
    alwaysStrict: boolean;
    exactOptionalPropertyTypes: boolean;
    noFallthroughCasesInSwitch: boolean;
    noImplicitAny: boolean;
    noImplicitOverride: boolean;
    noImplicitReturns: boolean;
    noImpliscitThis: boolean;
    noPropertyAccessFromIndexSignature: boolean;
    noUnusedLocals: boolean;
    noUnusedParameters: boolean;
    strict: boolean;
    strictBindCallApply: boolean;
    strictBuiltinIteratorReturn: boolean;
    strictFunctionTypes: boolean;
    strictNullChecks: boolean;
    strictPropertyInitialization: boolean;
    useUnknownInCatchVariables: boolean;
    allowArbitraryExtensions: boolean;
    allowImportingTsExtensions: boolean;
    allowUmdGlobalAccess: boolean;
    baseUrl: string;
    customConditions: string[];
    module: "none" 
          | "commonjs" 
          | "amd" 
          | "umd" 
          | "system" 
          | "es6" 
          | "es2015" 
          | "es2020" 
          | "es2022" 
          | "esnext" 
          | "node16" 
          | "node18" 
          | "node20" 
          | "nodenext" 
          | "preserve";
    moduleResolution: "classic" 
                    | "node" 
                    | "node10" 
                    | "node16" 
                    | "nodenext"
                    | "bundler";
    moduleSuffixes: string[];
    noResolve: boolean;
    noUncheckedSideEffectImports: boolean;
    paths: {
        [prop: string]: string[];
    };
    resolveJsonModule: boolean;
    resolvePackageJsonExports: boolean;
    resolvePackageJsonImports: boolean;
    rewriteRelativeImportExtensions: boolean;
    rootDir: string;
    rootDirs: string[];
    typeRoots: string[];
    types: string[];
    declaration: boolean;
    declarationDir: string;
    declarationMap: boolean;
    downlevelIteration: boolean;
    emitBOM: boolean;
    emitDeclarationOnly: boolean;
    importHelpers: boolean;
    inlineSourceMap: boolean;
    inlineSources: boolean;
    mapRoot: string;
    newLine: "crlf" 
           | "lf";
    noEmit: boolean;
    noEmitHelpers: boolean;
    noEmitOnError: boolean;
    outDir: string;
    outFile: string;
    preserveConstEnums: boolean;
    removeComments: boolean;
    sourceMap: boolean;
    sourceRoot: string;
    stripInternal: boolean;
    allowJs: boolean;
    checkJs: boolean;
    maxNodeModuleJsDepth: number;
    disableSizeLimit: boolean;
    plugins: {
        name: string;
        [key: string]: any;
    }[];
    allowSyntheticDefaultImports: boolean;
    erasableSyntaxOnly: boolean;
    esModuleInterop: boolean;
    forceConsistentCasingInFileNames: boolean;
    isolatedDeclarations: boolean;
    isolatedModules: boolean;
    preserveSymlinks: boolean;
    verbatimModuleSyntax: boolean;
    charset: "utf8";
    importsNotUsedAsValues: "remove" 
                          | "preserve" 
                          | "error";
    keyofStringsOnly: boolean;
    noImplicitUseStrict: boolean;
    noStrictGenericChecks: boolean;
    out: string;
    preserveValueImports: boolean;
    suppressExcessPropertyErrors: boolean;
    suppressImplicitAnyIndexErrors: boolean;
    emitDecoratorMetadata: boolean;
    experimentalDecorators: boolean;
    jsx: "preserve" 
       | "react" 
       | "react-native" 
       | "react-jsx" 
       | "react-jsxdev";
    jsxFactory: string;
    jsxFragmentFactory: string;
    jsxImportSource: string;
    lib: string[];
    libReplacement: boolean;
    moduleDetection: "auto" 
                   | "legacy" 
                   | "force";
    noLib: boolean;
    reactNamespace: string;
    target: "es3" 
          | "es5" 
          | "es6" 
          | "es2015" 
          | "es2016" 
          | "es2017" 
          | "es2018" 
          | "es2019" 
          | "es2020" 
          | "es2021" 
          | "es2022" 
          | "es2023" 
          | "es2024" 
          | "esnext";
    useDefineForClassFields: boolean;
    diagnostics: boolean;
    explainFiles: boolean;
    extendedDiagnostics: boolean;
    generateCpuProfile: string;
    generateTrace: boolean;
    listEmittedFiles: boolean;
    listFiles: boolean;
    noCheck: boolean;
    traceResolution: boolean;
    composite: boolean;
    disableReferencedProjectLoad: boolean;
    disableSolutionSearching: boolean;
    disableSourceOfProjectReferenceRedirect: boolean;
    incremental: boolean;
    tsBuildInfoFile: string;
    noErrorTruncation: boolean;
    preserveWatchOutput: boolean;
    pretty: boolean;
    skipDefaultLibCheck: boolean;
    skipLibCheck: boolean;
}>
export type WatchOptions = Partial<{
    assumeChangesOnlyAffectDirectDependencies: boolean;
    watchFile: "fixedpollinginterval" | "prioritypollinginterval" | "dynamicprioritypolling" | "fixedchunksizepolling" | "usefsevents" | "usefseventsonparentdirectory";
    watchDirectory: "usefsevents" | "fixedpollinginterval" | "dynamicprioritypolling" | "fixedchunksizepolling";
    fallbackPolling: "fixedinterval" | "priorityinterval" | "dynamicpriority" | "fixedchunksize";
    synchronousWatchDirectory: boolean;
    excludeDirectories: string[];
    excludeFiles: string[];
}>
export type TypeAcquisition = Partial<{
    enable: boolean;
    include: string[];
    exclude: string[];
    disableFilenameBasedTypeAcquisition: boolean;
}>